### ISSUE TITLE
Add verbose, debug flag and logging capabilities for errors

### ISSUE THREAD

**Issue by litneet64** [greatscottgadgets/cynthion#159]
After installing and setting up cynthion on my host control machine, I ran the analyzer before installing Packetry in order to check if it was somehow installed by the previous setup or pip install command but no but no new program nor window spawned. It also didn't show a message error neither, but it did show a success message and no more info.

![image](https://github.com/user-attachments/assets/eef670b9-08c2-4815-a04a-0c4fe79fbe9c)

Of course looking at the documentation for running the analyzer mentions that you need to have Packetry installed before using this functionality, however I think the cynthion client should also error when those requirements aren't met before even trying to run. Perhaps even a flag for enabling debugging or verbose information of what's happening underneath would also be of use.

Also, a separate issue could be created for including the setup of all required libraries and software (packetry + facedancer) with just one command (perhaps adding it to the setup subcommand), as these are part of the core functionality for cynthion as of now.

**Comment by martinling** [comment]
I think you're misunderstanding what that command is for.

Your Cynthion arrives with the analyzer gateware pre-loaded in flash. To use the analyzer you only need to run Packetry.

The `cynthion run` command is used to load different gateware into the FPGA's configuration RAM. If you had something other than the analyzer stored in the flash, you'd use `cynthion run analyzer` to run the analyzer gateware instead.

The command is succeeding as expected. It's not supposed to do anything else.

I think the issue here is that the documentation needs to be clearer.
